### ISSUE TITLE
请问大神怎么启动项目，谢谢

### ISSUE THREAD

**Issue by singer-coder** [F-loat/anonchat#1]
我看到里面一个客户端文件夹，一个server端文件夹，两个里面我都分别npm install，但是怎么去运行啊，server里面我用npm run dev 终端显示是
$ npm run dev

> anonchat-server@1.0.0 dev C:\Users\ABCDEFG丶\Desktop\anonchat-master\server
> nodemon index.js

[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`

但是客户端npm run server 就不对了，pack.json里写的是server啊 求大神指导，在线等

**Comment by F-loat** [comment]
客户端是 `npm run serve`，新版 vue-cli 生成的模板默认改成这个命令了

**Comment by singer-coder** [comment]
谢谢大神
