### ISSUE TITLE
server和client都运行了，点击开始聊天却一直在匹配怎回事啊大神

### ISSUE THREAD

**Issue by singer-coder** [F-loat/anonchat#2]
server和client都运行了，点击开始聊天却一直在匹配怎回事啊大神

**Comment by F-loat** [comment]
因为要有两个以上的人在线才行，你可以电脑和手机或者多开个浏览器这样

**Comment by singer-coder** [comment]
嗷嗷，谢谢大神指点

**Comment by singer-coder** [comment]
大神，我用了手机连接同样的IP地址测试，但是电脑和手机都是在匹配中，终端也没有什么变化
ABCDEFG丶@ABCDEFGؼ MINGW64 ~/Desktop/anonchat-master/server
$ npm run dev

> anonchat-server@1.0.0 dev C:\Users\ABCDEFG丶\Desktop\anonchat-master\server
> nodemon index.js

[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
求大神指导菜鸟。。。。谢谢。。。

**Comment by F-loat** [comment]
线上的那个你试试可以不，我晚一点再测试下

**Comment by singer-coder** [comment]
大神方便加下微信或者qq不

**Comment by F-loat** [comment]
我微信号 CMY-46，不过我待会儿有点事，晚一点再回复你

**Comment by singer-coder** [comment]
好的，谢谢，大神线上的没问题

**Comment by F-loat** [comment]
好像异性才会匹配到？具体的不太记得了

**Comment by singer-coder** [comment]
我用自己的ip试了异性也是不行，我就奇怪了，线上的可以匹配

**Comment by singer-coder** [comment]
然后过了一会报了这个错
![image](https://user-images.githubusercontent.com/24286620/39662076-1a2feaa2-508f-11e8-98f3-ef3bf756f898.png)
大神求教谢谢

**Comment by singer-coder** [comment]
network报错是
![image](https://user-images.githubusercontent.com/24286620/39662149-ef61952c-508f-11e8-86df-a4bba0be8687.png)
我ip和端口都改成192.168.1.98:8080,但是报错却又localhost:3000,我都没找到哪个地方的

**Comment by singer-coder** [comment]
大神我的本地也可以匹配了，刚才可能是因为开的终端端口占用，或者就是ip有问题，我关了几个终端窗口可以了，大神这个功能很厉害。。。。跪了

**Comment by F-loat** [comment]
当时仿 即刻 里的一个活动模块做的，只是实现了基本的功能，实际用的话拓展一下会更好

**Comment by singer-coder** [comment]
大神膜拜，谢谢！
